from .application_exceptions import (
    ApplicationError,
    EmailAlreadyExistsError,
    MissingRequiredFieldError,
    UserNotFoundError,
    IncorrectPasswordProvidedError,
    ErrorSendingMessageToWhatsapp,
    ExternalServiceError,
    InvalidPhoneNumberError,
    InvalidVerificationCodeError,
    UserAlreadyHasPhoneNumberError,
    NoVerificationCodeWasGeneratedError,
    MaxAttemptsReachedError,
    CodeExpiredError,
    UnhandledConfigurationValueError,
    SubscriptionNotFoundError,
    ActiveSubscriptionAlreadyExistsError,
    PhoneAlreadyRegisteredError,
    ScenarioNotFoundError,
    ScenarioKeyAlreadyExistsError,
    ScenarioPermissionDeniedError,
    OAuthConfigurationError,
    OAuthAuthenticationError,
)

from .send_email_exceptions import (
    SendEmailError,
    SMTPConnectionError,
    SMTPAuthenticationError,
    InvalidEmailAddressError,
    EmailSendingTimeoutError,
)

from .worker_exceptions import (
    WorkerError,
    ConversationManagerError,
    SessionActiveError,
    SessionStateInvalidError,
    AiWithQuotaLimitReachedError,
    CommandDoesNotExistError,
    GlobalIALockError,
    UserBannedError,
    RetryWhitoutCountAttempt,
    RetryCountAttempt,
)
