from .custom_exceptions import (
    ApplicationError,
    EmailAlreadyExistsError,
    MissingRequiredFieldError,
    UserNotFoundError,
    IncorrectPasswordProvidedError,
    ErrorSendingMessageToWhatsapp,
    ExternalServiceError,
    InvalidPhoneNumberError,
    InvalidVerificationCodeError,
    UserAlreadyHasPhoneNumberError,
    NoVerificationCodeWasGeneratedError,
    MaxAttemptsReachedError,
    CodeExpiredError,
    UnhandledConfigurationValueError,
    AiWithQuotaLimitReachedError,
)
