@echo off

echo Ativando ambiente virtual...
call venv\Scripts\activate

echo Criando schema do banco...
python -m external.database.scripts.create_schema

echo Criando tabelas...
python -m external.database.scripts.create_tables

echo Subindo aplicacao...
python app.py
