"""Implementar novas colunas na tabela plan e realizar link com tabela subscriptions

Revision ID: 31844629f7c9
Revises: a23726eae489
Create Date: 2026-04-05 10:49:51.996757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31844629f7c9'
down_revision = 'a23726eae489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('billing_cycle', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('message_limit', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('trial_days', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.drop_column('active')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('subscriptions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'plans', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subscriptions_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('trial_days')
        batch_op.drop_column('is_active')
        batch_op.drop_column('features')
        batch_op.drop_column('message_limit')
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('currency')
        batch_op.drop_column('description')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
