"""adding_externalid_at_subscription_table

Revision ID: 5a221c9b1716
Revises: e1f2d3c4b5a6
Create Date: 2026-05-09 16:36:07.999837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a221c9b1716'
down_revision = 'e1f2d3c4b5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['external_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
