"""Adicionando is_free no plan model

Revision ID: 60c4c6adc4fb
Revises: cce89e256162
Create Date: 2026-04-27 15:46:45.899823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c4c6adc4fb'
down_revision = 'cce89e256162'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Adiciona a coluna permitindo NULL inicialmente
    op.add_column('plans', sa.Column('is_free', sa.Boolean(), nullable=True))
    
    # 2. Define um valor padrão (ex: False) para todas as linhas existentes
    # Isso garante que nenhuma linha fique com NULL
    op.execute("UPDATE plans SET is_free = False")
    
    # 3. Agora que não existem mais NULLs, alteramos para NOT NULL
    op.alter_column('plans', 'is_free', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('is_free')

    # ### end Alembic commands ###
