"""Alterar tipo do valor price do plan

Revision ID: 916f170befcc
Revises: 7d6920d8ab95
Create Date: 2026-04-05 12:30:56.926455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916f170befcc'
down_revision = '7d6920d8ab95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
