"""Criando nova tabela de tipo de sessão

Revision ID: a23726eae489
Revises: bc9d786c55cd
Create Date: 2026-03-08 12:27:17.081472

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a23726eae489'
down_revision = 'bc9d786c55cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    session_type_enum = postgresql.ENUM('FREE_TALK', 'SCENARIO', name='conversationsessionstype')
    session_type_enum.create(op.get_bind())
    
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_type', sa.Enum('FREE_TALK', 'SCENARIO', name='conversationsessionstype'), nullable=False))
        batch_op.add_column(sa.Column('context_description', sa.Text(), nullable=True))
        batch_op.drop_column('scenario_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM(name='conversationsessionstype').drop(op.get_bind())
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_key', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('context_description')
        batch_op.drop_column('session_type')

    # ### end Alembic commands ###
