"""add is_allowed column to message_history

Revision ID: ae0adf1654d8
Revises: c5117272ee3a
Create Date: 2026-02-04 18:02:40.954981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0adf1654d8'
down_revision = 'c5117272ee3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.create_index(batch_op.f('ix_messages_history_is_allowed'), ['is_allowed'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_history_is_allowed'))
        batch_op.drop_column('is_allowed')

    # ### end Alembic commands ###
