"""add_sessions_and_scenarios

Revision ID: bc9d786c55cd
Revises: eb654ef80f5f
Create Date: 2026-03-07 19:03:41.444964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9d786c55cd'
down_revision = 'eb654ef80f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_role_definition', sa.Text(), nullable=False),
    sa.Column('user_role_definition', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_contexts_key'), ['key'], unique=True)

    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRACTICING', 'EXAM', 'COMPLETED', 'EXPIRED', 'CANCELLED', 'AWAITING_DEFINITION', name='conversationsessionsstate'), nullable=False),
    sa.Column('scenario_key', sa.Text(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario_contexts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_sessions_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('messages_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'conversation_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_is_active'))

    op.drop_table('conversation_sessions')
    with op.batch_alter_table('scenario_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_contexts_key'))

    op.drop_table('scenario_contexts')
    # ### end Alembic commands ###
